name: rpb
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2023.12.12
  - cudatoolkit=10.1.243
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2023.1.0
  - jpeg=9b
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuv=1.44.2
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.13
  - pillow=9.3.0
  - pip=23.3.1
  - python=3.8.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - fire==0.5.0
      - scipy==1.10.1
      - six==1.16.0
      - termcolor==2.4.0
      - torch==1.9.0+cu111
      - torchaudio==0.9.0
      - torchvision==0.10.0+cu111
      - tqdm==4.61.0